development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: grassroots_dev
  pool: 5
  username: grassroots_user
  password: password
  host: lookingglass.local

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: grassroots_prod
  pool: 5
  username: grassroots_user
  password: password
  host: localhost

